TRY e CATCH

Funcionam como um if e else para tratamento de promises.

Caso a promise retorne Fulfilled o bloco try é executado, caso dê algum erro (Rejected), o bloco try é ignorado e executa o bloco catch.

Sintaxe:

Em uma callback -

evento.addEventListener("click", async () => {

    try {
        const response = await fetch(URL);
        const data = await response.json();
        resto da função....

    } catch (error) {
        throw new error = `${error.message}`;
        ou o que quiser que retorne aqui..
    }    
})

em funções normais -

const cep = '30130-010'; 
try {
  const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`);
  const data = await response.json();
  console.log(data);
} catch(error) {
  console.log(error)
}
